language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

sudo: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2==0.5.1; fi
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coverage python-coveralls

script: nosetests tests/unit --cover-erase --with-coverage --cover-package awscli

after_success: coveralls
