language: python
sudo: false

matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
      dist: xenial
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: xenial
    - python: 3.5
      dist: xenial
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi
  - pip install codecov
install:
  - python scripts/ci/install
script: python scripts/ci/run-tests
after_success:
  - rm tests/coverage.xml && mv tests/.coverage ./ && codecov
