name: "Set labels and assignees"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          parameters: >
            [
             {"area":"s3", "keywords": ["s3", "bucket"], "labels": ["s3"]},
             {"area": "ec2", "keywords": ["ec2", "instance"], "labels": ["ec2"]},
             {"area": "acm", "keywords": ["acm"], "labels": ["acm"]},
             {"area": "amplify", "keywords": ["amplify"], "labels": ["amplify"]},
             {"area": "apigateway", "keywords": ["apigateway"], "labels": ["apigateway"]},
             {"area": "appflow", "keywords": ["appflow"], "labels": ["appflow"]},
             {"area": "autocomplete", "keywords": ["autocomplete"], "labels": ["autocomplete"]},
             {"area": "autoscaling", "keywords": ["autoscaling"], "labels": ["autoscaling"]},
             {"area": "certs", "keywords": ["certs"], "labels": ["certs"]},
             {"area": "cloud9", "keywords": ["cloud9"], "labels": ["cloud9"]},
             {"area": "cloudcontrol", "keywords": ["cloudcontrol"], "labels": ["cloudcontrol"]},
             {"area": "cloudformation", "keywords": ["cloudformation"], "labels": ["cloudformation"]},
             {"area": "cloudfront", "keywords": ["cloudfront"], "labels": ["cloudfront"]},
             {"area": "cloudsearch", "keywords": ["cloudsearch"], "labels": ["cloudsearch"]},
             {"area": "cloudtrail", "keywords": ["cloudtrail"], "labels": ["cloudtrail"]},
             {"area": "cloudtrail", "keywords": ["cloudtrail"], "labels": ["cloudtrail"]},
             {"area": "cloudwatch", "keywords": ["cloudwatch"], "labels": ["cloudwatch"]},
             {"area": "codeartifact", "keywords": ["codeartifact"], "labels": ["codeartifact"]},
             {"area": "codebuild", "keywords": ["codebuild"], "labels": ["codebuild"]},
             {"area": "codecommit", "keywords": ["codecommit"], "labels": ["codecommit"]},
             {"area": "codedeploy", "keywords": ["codedeploy"], "labels": ["codedeploy"]},
             {"area": "cognito", "keywords": ["cognito"], "labels": ["cognito"]},
             {"area": "cognito-idp", "keywords": ["cognito-idp"], "labels": ["cognito-idp"]},
             {"area": "configservice", "keywords": ["configservice"], "labels": ["configservice"]},
             {"area": "devicefarm", "keywords": ["devicefarm"], "labels": ["devicefarm"]},
             {"area": "directconnect", "keywords": ["directconnect"], "labels": ["directconnect"]},
             {"area": "docdb", "keywords": ["docdb"], "labels": ["docdb"]},
             {"area": "docker", "keywords": ["docker"], "labels": ["docker"]},
             {"area": "dynamodb", "keywords": ["dynamodb"], "labels": ["dynamodb"]},
             {"area": "ec2", "keywords": ["ec2"], "labels": ["ec2"]},
             {"area": "ecr", "keywords": ["ecr"], "labels": ["ecr"]},
             {"area": "ecs", "keywords": ["ecs"], "labels": ["ecs"]},
             {"area": "efs", "keywords": ["efs"], "labels": ["efs"]},
             {"area": "eks", "keywords": ["eks"], "labels": ["eks"]},
             {"area": "elasticache", "keywords": ["elasticache"], "labels": ["elasticache"]},
             {"area": "elasticbeanstalk", "keywords": ["elasticbeanstalk"], "labels": ["elasticbeanstalk"]},
             {"area": "elbv2", "keywords": ["elbv2"], "labels": ["elbv2"]},
             {"area": "emr", "keywords": ["emr"], "labels": ["emr"]},
             {"area": "fsx", "keywords": ["fsx"], "labels": ["fsx"]},
             {"area": "gamelift", "keywords": ["gamelift"], "labels": ["gamelift"]},
             {"area": "glacier", "keywords": ["glacier"], "labels": ["glacier"]},
             {"area": "globalaccelerator", "keywords": ["globalaccelerator"], "labels": ["globalaccelerator"]},
             {"area": "glue", "keywords": ["glue"], "labels": ["glue"]},
             {"area": "grafana", "keywords": ["grafana"], "labels": ["grafana"]},
             {"area": "greengrass", "keywords": ["greengrass"], "labels": ["greengrass"]},
             {"area": "iam", "keywords": ["iam"], "labels": ["iam"]},
             {"area": "iot", "keywords": ["iot"], "labels": ["iot"]},
             {"area": "jmespath", "keywords": ["jmespath"], "labels": ["jmespath"]},
             {"area": "kafka", "keywords": ["kafka"], "labels": ["kafka"]},
             {"area": "kinesis", "keywords": ["kinesis"], "labels": ["kinesis"]},
             {"area": "kms", "keywords": ["kms"], "labels": ["kms"]},
             {"area": "lakeformation", "keywords": ["lakeformation"], "labels": ["lakeformation"]},
             {"area": "lambda", "keywords": ["lambda"], "labels": ["lambda"]},
             {"area": "lightsail", "keywords": ["lightsail"], "labels": ["lightsail"]},
             {"area": "medium", "keywords": ["medium"], "labels": ["medium"]},
             {"area": "mq", "keywords": ["mq"], "labels": ["mq"]},
             {"area": "mturk", "keywords": ["mturk"], "labels": ["mturk"]},
             {"area": "mwaa", "keywords": ["mwaa"], "labels": ["mwaa"]},
             {"area": "neptune", "keywords": ["neptune"], "labels": ["neptune"]},
             {"area": "presign", "keywords": ["presign"], "labels": ["presign"]},
             {"area": "pricing", "keywords": ["pricing"], "labels": ["pricing"]},
             {"area": "pyinstaller", "keywords": ["pyinstaller"], "labels": ["pyinstaller"]},
             {"area": "quicksight", "keywords": ["quicksight"], "labels": ["quicksight"]},
             {"area": "rds", "keywords": ["rds"], "labels": ["rds"]},
             {"area": "redshift-data", "keywords": ["redshift-data"], "labels": ["redshift-data"]},
             {"area": "rekognition", "keywords": ["rekognition"], "labels": ["rekognition"]},
             {"area": "resourcegroupstaggingapi", "keywords": ["resourcegroupstaggingapi"], "labels": ["resourcegroupstaggingapi"]},
             {"area": "route53", "keywords": ["route53"], "labels": ["route53"]},
             {"area": "route53domains", "keywords": ["route53domains"], "labels": ["route53domains"]},
             {"area": "s3", "keywords": ["s3"], "labels": ["s3"]},
             {"area": "sagemaker", "keywords": ["sagemaker"], "labels": ["sagemaker"]},
             {"area": "schemas", "keywords": ["schemas"], "labels": ["schemas"]},
             {"area": "secretsmanager", "keywords": ["secretsmanager"], "labels": ["secretsmanager"]},
             {"area": "SECURITY", "keywords": ["SECURITY"], "labels": ["SECURITY"]},
             {"area": "serverlessrepo", "keywords": ["serverlessrepo"], "labels": ["serverlessrepo"]},
             {"area": "service-api", "keywords": ["service-api"], "labels": ["service-api"]},
             {"area": "servicecatalog", "keywords": ["servicecatalog"], "labels": ["servicecatalog"]},
             {"area": "servicediscovery", "keywords": ["servicediscovery"], "labels": ["servicediscovery"]},
             {"area": "servicequota", "keywords": ["servicequota"], "labels": ["servicequota"]},
             {"area": "session-manager-plugin", "keywords": ["session-manager-plugin"], "labels": ["session-manager-plugin"]},
             {"area": "sesv2", "keywords": ["sesv2"], "labels": ["sesv2"]},
             {"area": "snap", "keywords": ["snap"], "labels": ["snap"]},
             {"area": "sns", "keywords": ["sns"], "labels": ["sns"]},
             {"area": "spam", "keywords": ["spam"], "labels": ["spam"]},
             {"area": "sqs", "keywords": ["sqs"], "labels": ["sqs"]},
             {"area": "ssm", "keywords": ["ssm"], "labels": ["ssm"]},
             {"area": "ssm start-session", "keywords": ["ssm start-session"], "labels": ["ssm start-session"]},
             {"area": "sso", "keywords": ["sso"], "labels": ["sso"]},
             {"area": "sts", "keywords": ["sts"], "labels": ["sts"]},
             {"area": "transcribe", "keywords": ["transcribe"], "labels": ["transcribe"]},
             {"area": "transfer", "keywords": ["transfer"], "labels": ["transfer"]},
             {"area": "wafv2", "keywords": ["wafv2"], "labels": ["wafv2"]},
             {"area": "waiter", "keywords": ["waiter"], "labels": ["waiter"]},
             {"area": "wellarchitected", "keywords": ["wellarchitected"], "labels": ["wellarchitected"]},
             {"area": "workdocs", "keywords": ["workdocs"], "labels": ["workdocs"]},
             {"area": "workspaces", "keywords": ["workspaces"], "labels": ["workspaces"]},
             {"area": "pager", "keywords": ["pager"], "labels": ["pager"]},
             {"area": "configuration", "keywords": ["configuration", "configure"], "labels": ["configuration"]},
             {"area": "events", "keywords": ["events", "calling"], "labels": ["events"]},
             {"area": "feature-request", "keywords": ["feature-request", "would be", "currently", "add", "would like", "d like", "to be able to"], "labels": ["feature-request"]},
             {"area": "bug", "keywords": ["bug", "should work", "not working", "test failed", "breaks", "fails", "broken"], "labels": ["bug"]},
             {"area": "installation", "keywords": ["installation", "installed", "installing"], "labels": ["installation"]},
             {"area": "logs", "keywords": ["logs"], "labels": ["logs"]},
             {"area": "windows", "keywords": ["windows"], "labels": ["windows"]},
             {"area": "wizard", "keywords": ["wizard"], "labels": ["wizard"]},
             {"area": "v1", "keywords": ["v1"], "labels": ["v1"]},
             {"area": "v2", "keywords": ["v2"], "labels": ["v2"]},
             {"area": "v3", "keywords": ["v3"], "labels": ["v3"]},
             {"area": "documentation", "keywords": ["documentation", "typo"], "labels": ["documentation"]}
             ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          excluded-expressions: "[ TypeScript | Java | Python ]"